In [ ]:
import pandas as pd
df=pd.read_csv("/content/Ecommerce Purchases")
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [ ]:
df.iat[1,4]

'Fletcher, Richards and Whitaker'

In [ ]:
(df["Job"]=="Engineer"). sum()
#mine wrong

0

Job title contain engineer

In [ ]:
len(df[df["Job"].str.contains("engineer",case=False)])

984

Find email of person with the ip 132.207.160.22

In [ ]:
df[df["IP Address"]=="132.207.160.22"]["Email"]

2    amymiller@morales-harrison.com
Name: Email, dtype: object

How many people have Master card as their  credit card provider and made purchase above 50

In [ ]:
df. columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [ ]:
df["CC Provider"]

0                      JCB 16 digit
1                        Mastercard
2                      JCB 16 digit
3                          Discover
4       Diners Club / Carte Blanche
                   ...
9995                   JCB 15 digit
9996                   JCB 16 digit
9997                  VISA 16 digit
9998               American Express
9999                   JCB 15 digit
Name: CC Provider, Length: 10000, dtype: object

In [ ]:
len(df[(df["CC Provider"]=="Mastercard") &(df["Purchase Price"]>50)])

405

In [ ]:
df[(df["CC Provider"]=="Mastercard")
 &(df["Purchase Price"]>50)].count()

Address             405
Lot                 405
AM or PM            405
Browser Info        405
Company             405
Credit Card         405
CC Exp Date         405
CC Security Code    405
CC Provider         405
Email               405
Job                 405
IP Address          405
Language            405
Purchase Price      405
dtype: int64

Find email of person credit no 4664825258997302

In [ ]:
df[df["Credit Card"]==4664825258997302]["Email"]

9992    bberry@wright.net
Name: Email, dtype: object

how many people purchase am, pm

In [ ]:
a=len(df[df['AM or PM']=="AM"]["Email"])
a  #AM

4932

In [ ]:
T=len(df['AM or PM'])
T

10000

In [ ]:
Pm=T-a
Pm   #PM

5068

In [ ]:
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

How many people credit card expires in 2020

In [ ]:
df["CC Exp Date"].spilt("/")

AttributeError: 'Series' object has no attribute 'spilt'

In [ ]:
def f():
    c=0
    for i in df["CC Exp Date"]:

       # print (i.split("/")[1])
         s=i.split("/")[1]
         for a in s:
             if a==20:
                c=c+1

         print(c)

f()
#mine wrong

In [ ]:
def f() :
     c=0
     for i in df["CC Exp Date"]:
         if i.split("/")[1]=='20':
            c=c+1
     print(c)


f()

In [ ]:
len(df[df["CC Exp Date"].apply(lambda x:x[3:]=="20")])

#slice because 20/20  01234 it it's last 2 index

Top 5 most popular email provider (gmail.com yahho.com)

In [ ]:

def s():
    for i in df["Email"]:
       S=i.split("@")[1]
       print(S)
      # l=[]

      # l.append(S)
      # print(list(l))
#valuecount to find most
s()#Mine

In [1]:
ls=[]
for i in df["Email"]:
      ls.append(i.split("@")[1])

NameError: name 'df' is not defined

In [ ]:
df["temp"]=ls
df. head()

In [ ]:
df["temp"].value_counts().head()

In [ ]:
df["Email"].apply(lambda x:x.split("@") [1]).value_counts().head(5)

In [ ]:
L=df.nlargest(5,"Job")
L.head()